### ISSUE TITLE
Add comments to drive.py

### ISSUE THREAD

**Issue by yazeedalrubyli** [yazeedalrubyli/SDRC#1]

**Comment by Abdalhad** [comment]
Traceback (most recent call last):
  File "./drive.py", line 140, in <module>
    carCol = Collector()
  File "./drive.py", line 109, in __init__
    file = open(fileName, 'a')
IOError: [Errno 2] No such file or directory: 'data/steering.csv'


give this error !
when write ./drive.py -c 
what is the solution.

**Comment by yazeedalrubyli** [comment]
You have to collect the data using manual mode (-c,--collect)....then after hopefully a few minutes of training collecting data...switch to autonomous mode (-d,--drive).

@Abdalhad

**Comment by abhishekjain98** [comment]
Hi,
I am new to raspberry pi.
I will be very greatful to you if you help me in understanding the data collection code.
